
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...1
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...1
INFO:tensorflow:...0
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...4
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...4
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...4
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...4
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...4
INFO:tensorflow:...1
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...4
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...4
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...0
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...2
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...3
INFO:tensorflow:...2
INFO:tensorflow:...1
INFO:tensorflow:...3